name: My Testing First CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: print node version
        run: node --version
      - name: print npm version
        run: npm --version
